Computing job 703694 on ant12
2023-02-21 09:28:03.327106: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-21 09:28:03.327152: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-21 09:28:06.601013: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-21 09:28:06.601056: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-21 09:28:06.601075: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ant12): /proc/driver/nvidia/version does not exist
2023-02-21 09:28:06.601429: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-21 09:28:07.383217: E tensorflow/core/framework/node_def_util.cc:629] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node AssignNewValue}}
2023-02-21 09:28:09.172193: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
 1/32 [..............................] - ETA: 11s - loss: 0.1883 - accuracy: 0.968822/32 [===================>..........] - ETA: 0s - loss: 0.3022 - accuracy: 0.9375 32/32 [==============================] - 0s 2ms/step - loss: 0.2993 - accuracy: 0.9410
Accuracy on train dataset:  0.9409999847412109
  1/313 [..............................] - ETA: 4s - loss: 1.2280 - accuracy: 0.6562 23/313 [=>............................] - ETA: 0s - loss: 1.3537 - accuracy: 0.5299 44/313 [===>..........................] - ETA: 0s - loss: 1.3317 - accuracy: 0.5440 66/313 [=====>........................] - ETA: 0s - loss: 1.3443 - accuracy: 0.5436 88/313 [=======>......................] - ETA: 0s - loss: 1.3653 - accuracy: 0.5408110/313 [=========>....................] - ETA: 0s - loss: 1.3655 - accuracy: 0.5378133/313 [===========>..................] - ETA: 0s - loss: 1.3480 - accuracy: 0.5456156/313 [=============>................] - ETA: 0s - loss: 1.3342 - accuracy: 0.5489179/313 [================>.............] - ETA: 0s - loss: 1.3431 - accuracy: 0.5485201/313 [==================>...........] - ETA: 0s - loss: 1.3446 - accuracy: 0.5462224/313 [====================>.........] - ETA: 0s - loss: 1.3457 - accuracy: 0.5449247/313 [======================>.......] - ETA: 0s - loss: 1.3358 - accuracy: 0.5480270/313 [========================>.....] - ETA: 0s - loss: 1.3435 - accuracy: 0.5447290/313 [==========================>...] - ETA: 0s - loss: 1.3432 - accuracy: 0.5436308/313 [============================>.] - ETA: 0s - loss: 1.3432 - accuracy: 0.5432313/313 [==============================] - 1s 2ms/step - loss: 1.3440 - accuracy: 0.5426
2023-02-21 09:28:12.687326: E tensorflow/core/framework/node_def_util.cc:629] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node AssignNewValue}}
Accuracy on test dataset:  0.5425999760627747
  0%|          | 0/50 [00:00<?, ?it/s]  2%|▏         | 1/50 [00:00<00:19,  2.53it/s]  4%|▍         | 2/50 [00:00<00:18,  2.58it/s]  6%|▌         | 3/50 [00:01<00:18,  2.55it/s]  8%|▊         | 4/50 [00:01<00:18,  2.52it/s] 10%|█         | 5/50 [00:01<00:17,  2.52it/s] 12%|█▏        | 6/50 [00:02<00:17,  2.51it/s] 14%|█▍        | 7/50 [00:02<00:17,  2.42it/s] 16%|█▌        | 8/50 [00:03<00:17,  2.40it/s] 18%|█▊        | 9/50 [00:03<00:16,  2.42it/s] 20%|██        | 10/50 [00:04<00:16,  2.43it/s] 22%|██▏       | 11/50 [00:04<00:15,  2.45it/s] 24%|██▍       | 12/50 [00:04<00:15,  2.46it/s] 26%|██▌       | 13/50 [00:05<00:15,  2.46it/s] 28%|██▊       | 14/50 [00:05<00:14,  2.48it/s] 30%|███       | 15/50 [00:06<00:14,  2.49it/s] 32%|███▏      | 16/50 [00:06<00:13,  2.49it/s] 34%|███▍      | 17/50 [00:06<00:13,  2.49it/s] 36%|███▌      | 18/50 [00:07<00:12,  2.51it/s] 38%|███▊      | 19/50 [00:07<00:12,  2.50it/s] 40%|████      | 20/50 [00:08<00:11,  2.51it/s] 42%|████▏     | 21/50 [00:08<00:11,  2.49it/s] 44%|████▍     | 22/50 [00:08<00:11,  2.50it/s] 46%|████▌     | 23/50 [00:09<00:10,  2.51it/s] 48%|████▊     | 24/50 [00:09<00:10,  2.51it/s] 50%|█████     | 25/50 [00:10<00:09,  2.52it/s] 52%|█████▏    | 26/50 [00:10<00:09,  2.52it/s] 54%|█████▍    | 27/50 [00:10<00:09,  2.52it/s] 56%|█████▌    | 28/50 [00:11<00:08,  2.52it/s] 58%|█████▊    | 29/50 [00:11<00:08,  2.52it/s] 60%|██████    | 30/50 [00:12<00:07,  2.53it/s] 62%|██████▏   | 31/50 [00:12<00:07,  2.54it/s] 64%|██████▍   | 32/50 [00:12<00:07,  2.50it/s] 66%|██████▌   | 33/50 [00:13<00:06,  2.52it/s] 68%|██████▊   | 34/50 [00:13<00:06,  2.52it/s] 70%|███████   | 35/50 [00:14<00:05,  2.53it/s] 72%|███████▏  | 36/50 [00:14<00:05,  2.53it/s] 74%|███████▍  | 37/50 [00:14<00:05,  2.53it/s] 76%|███████▌  | 38/50 [00:15<00:04,  2.52it/s] 78%|███████▊  | 39/50 [00:15<00:04,  2.52it/s] 80%|████████  | 40/50 [00:15<00:03,  2.51it/s] 82%|████████▏ | 41/50 [00:16<00:03,  2.52it/s] 84%|████████▍ | 42/50 [00:16<00:03,  2.53it/s] 86%|████████▌ | 43/50 [00:17<00:02,  2.54it/s] 88%|████████▊ | 44/50 [00:17<00:02,  2.54it/s] 90%|█████████ | 45/50 [00:17<00:01,  2.54it/s] 92%|█████████▏| 46/50 [00:18<00:01,  2.54it/s] 94%|█████████▍| 47/50 [00:18<00:01,  2.55it/s] 96%|█████████▌| 48/50 [00:19<00:00,  2.55it/s] 98%|█████████▊| 49/50 [00:19<00:00,  2.56it/s]100%|██████████| 50/50 [00:19<00:00,  2.55it/s]100%|██████████| 50/50 [00:19<00:00,  2.51it/s]
  0%|          | 0/50 [00:00<?, ?it/s]  4%|▍         | 2/50 [00:00<00:03, 13.57it/s]  8%|▊         | 4/50 [00:00<00:03, 13.54it/s] 12%|█▏        | 6/50 [00:00<00:03, 13.64it/s] 16%|█▌        | 8/50 [00:00<00:03, 13.70it/s] 20%|██        | 10/50 [00:00<00:02, 13.73it/s] 24%|██▍       | 12/50 [00:00<00:02, 13.63it/s] 28%|██▊       | 14/50 [00:01<00:02, 13.60it/s] 32%|███▏      | 16/50 [00:01<00:02, 13.54it/s] 36%|███▌      | 18/50 [00:01<00:02, 13.49it/s] 40%|████      | 20/50 [00:01<00:02, 13.44it/s] 44%|████▍     | 22/50 [00:01<00:02, 13.42it/s] 48%|████▊     | 24/50 [00:01<00:01, 13.38it/s] 52%|█████▏    | 26/50 [00:01<00:01, 13.45it/s] 56%|█████▌    | 28/50 [00:02<00:01, 13.52it/s] 60%|██████    | 30/50 [00:02<00:01, 13.60it/s] 64%|██████▍   | 32/50 [00:02<00:01, 13.70it/s] 68%|██████▊   | 34/50 [00:02<00:01, 13.78it/s] 72%|███████▏  | 36/Ensembe could not be found at path: 
Ensemble will be trained now
50 [00:02<00:01, 13.83it/s] 76%|███████▌  | 38/50 [00:02<00:00, 13.81it/s] 80%|████████  | 40/50 [00:02<00:00, 13.81it/s] 84%|████████▍ | 42/50 [00:03<00:00, 13.79it/s] 88%|████████▊ | 44/50 [00:03<00:00, 13.80it/s] 92%|█████████▏| 46/50 [00:03<00:00, 13.87it/s] 96%|█████████▌| 48/50 [00:03<00:00, 13.83it/s]100%|██████████| 50/50 [00:03<00:00, 13.78it/s]100%|██████████| 50/50 [00:03<00:00, 13.67it/s]
Traceback (most recent call last):
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 35, in __init__
    range(num_members)]
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 34, in <listcomp>
    self.members = [tf.keras.models.load_model(path_to_ensemble + "/member_" + str(i)) for i in
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/saving/saved_model/load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 121, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /member_0/{saved_model.pbtxt|saved_model.pb}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 96, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ../models/classification/CNN_cifar100/cp.ckpt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluation_metrics.py", line 196, in <module>
    path_to_ensemble=path_to_dataAug_ens, X_val=x_val, y_val=y_val, val=True)
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 142, in __init__
    num_members, val)
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 42, in __init__
    self.init_new_ensemble(path_to_ensemble, X_train, y_train, X_val, y_val, build_model_function, num_members)
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 152, in init_new_ensemble
    self.init_members(build_model_function, num_members)
  File "/home/urz/hlichten/uncertainty/Ensemble.py", line 94, in init_members
    member.load_weights("../models/classification/CNN_cifar100/cp.ckpt")
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/engine/training.py", line 2329, in load_weights
    filepath, save_format = _detect_save_format(filepath)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/engine/training.py", line 3014, in _detect_save_format
    if _is_readable_tf_checkpoint(filepath):
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/engine/training.py", line 3035, in _is_readable_tf_checkpoint
    tf.compat.v1.train.NewCheckpointReader(filepath)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 100, in NewCheckpointReader
    error_translator(e)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ../models/classification/CNN_cifar100/cp.ckpt
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root)._default_save_signature
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).signatures.serving_default
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
srun: error: ant12: task 0: Exited with exit code 1
