Computing job 703693 on ant12
2023-02-21 09:25:42.755061: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-21 09:25:42.755114: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-21 09:25:49.201370: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-21 09:25:49.201414: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-21 09:25:49.201432: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ant12): /proc/driver/nvidia/version does not exist
2023-02-21 09:25:49.201773: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-21 09:25:50.002062: E tensorflow/core/framework/node_def_util.cc:629] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node AssignNewValue}}
2023-02-21 09:25:51.789003: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
 1/32 [..............................] - ETA: 11s - loss: 0.1883 - accuracy: 0.968823/32 [====================>.........] - ETA: 0s - loss: 0.3012 - accuracy: 0.9361 32/32 [==============================] - 0s 2ms/step - loss: 0.2993 - accuracy: 0.9410
Accuracy on train dataset:  0.9409999847412109
  1/313 [..............................] - ETA: 5s - loss: 1.2280 - accuracy: 0.6562 23/313 [=>............................] - ETA: 0s - loss: 1.3537 - accuracy: 0.5299 46/313 [===>..........................] - ETA: 0s - loss: 1.3205 - accuracy: 0.5462 69/313 [=====>........................] - ETA: 0s - loss: 1.3430 - accuracy: 0.5426 93/313 [=======>......................] - ETA: 0s - loss: 1.3615 - accuracy: 0.5403116/313 [==========>...................] - ETA: 0s - loss: 1.3609 - accuracy: 0.5396139/313 [============>.................] - ETA: 0s - loss: 1.3448 - accuracy: 0.5459162/313 [==============>...............] - ETA: 0s - loss: 1.3378 - accuracy: 0.5492186/313 [================>.............] - ETA: 0s - loss: 1.3438 - accuracy: 0.5467210/313 [===================>..........] - ETA: 0s - loss: 1.3406 - accuracy: 0.5466234/313 [=====================>........] - ETA: 0s - loss: 1.3401 - accuracy: 0.5461257/313 [=======================>......] - ETA: 0s - loss: 1.3394 - accuracy: 0.5457281/313 [=========================>....] - ETA: 0s - loss: 1.3463 - accuracy: 0.5435304/313 [============================>.] - ETA: 0s - loss: 1.3411 - accuracy: 0.5436313/313 [==============================] - 1s 2ms/step - loss: 1.3440 - accuracy: 0.5426
2023-02-21 09:25:53.935630: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ../models/classification/CNN_cifar10_1000: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<keras.layers.core.Dense object at 0x7fb120373198> and <keras.layers.core.Dense object at 0x7fb1202fd748>).
Accuracy on test dataset:  0.5425999760627747
Traceback (most recent call last):
  File "evaluation_metrics.py", line 176, in <module>
    model.load_weights(model_path)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/keras/engine/training.py", line 2331, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 1383, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 254, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 981, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 352, in restore_saveables
    validated_saveables).restore(self.save_path_tensor, self.options)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/saving/functional_saver.py", line 339, in restore
    restore_ops = restore_fn()
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/saving/functional_saver.py", line 323, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/saving/functional_saver.py", line 116, in restore
    restored_tensors, restored_shapes=None)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 132, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 309, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/urz/hlichten/vEnvTest/lib64/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1161, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (100,) and (10,) are incompatible
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root)._default_save_signature
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11._jit_compiled_convolution_op
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).signatures.serving_default
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-1.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-4.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-5.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-4.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-5.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-6.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-14.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-15.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-7.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-8.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-18.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-19.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-9.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-10.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-11.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-23.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-24.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-25.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-26.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-27.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-12.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-29.call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-13.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
srun: error: ant12: task 0: Exited with exit code 1
